events {}

http {
    # Define the group of servers for Load Balancing[cite: 1]
    upstream fastapi_cluster {
        server app1:8000;
        server app2:8000;
    }

    server {
        # Nginx will listen on port 80[cite: 1]
        listen 80;

        # Allow uploading larger image files
        client_max_body_size 20M;

        location / {
            # Route traffic to the upstream group defined above[cite: 1]
            proxy_pass http://fastapi_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}